### ISSUE TITLE
SFTP support?

### ISSUE THREAD

**Issue by merdes** [iJanki/FtpBundle#6]
Hey @iJanki !
As far as I can see here:
http://php.net/manual/en/ref.ftp.php

The library does not provide SFTP support. Is there a way to use it ?

I'm getting this error:

> Warning: ftp_login(): Non-anonymous sessions must use encryption.

**Comment by iJanki** [comment]
SFTP is completely different, this bundle will not cover it.

I think you would need this extension:

http://php.net/manual/en/function.ssh2-sftp.php
